### ISSUE TITLE
cannot import wand.image and wand.api

### ISSUE THREAD

**Issue by Ximoi** [hendrycks/robustness#18]
Hi， I meet some errors when I try to use create_imagenet_c.py on my own dataset. The bug follows and it seems ' MagickWand shared library not found'.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fuyi02/anaconda3/envs/vos-temp/lib/python2.7/site-packages/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/home/fuyi02/anaconda3/envs/vos-temp/lib/python2.7/site-packages/wand/api.py", line 1394, in <module>
    traceback.format_exc())
ImportError: MagickWand shared library not found or incompatible
Original exception was raised in:
Traceback (most recent call last):
  File "/home/fuyi02/anaconda3/envs/vos-temp/lib/python2.7/site-packages/wand/api.py", line 817, in <module>
    ctypes.c_void_p]  # PixelWand color
  File "/home/fuyi02/anaconda3/envs/vos-temp/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/home/fuyi02/anaconda3/envs/vos-temp/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: libMagickWand.so.2: undefined symbol: DrawSetBorderColor

My system is centos6.4.
I download the ImageMagick6 in 'https://github.com/ImageMagick/ImageMagick6' and install with'
cd ImageMagick-6
./configure --prefix=/usr --with-modules --with-perl=/usr/bin/perl --with-jp2 --enable-shared --disable-static --without-magick-plus-pus
make
make install'
then ' yum install ImageMagick-devel '

Can you tell me how to fix it, Thank you!

**Comment by Ximoi** [comment]
the wand is installed by 'pip install wand==0.4.4'
and I use anaconda to install all the package.
